name: Build and Push to Docker Hub


on:
  push:
    branches: [main] #only trigger on main branch pushes


jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx #modern Docker that supports multi-platform builds 
        uses: docker/login-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.mokgethwaliz}}
          password: ${{ secrets.mokgethwaliz}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfile 
          push: true
          tags: mokgethwaliz/customer-churn-fastapi:latest

    
